[project]
name = 'SkillProof'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.dispute-resolution]
path = 'contracts/dispute-resolution.clar'
clarity_version = 2
epoch = 2.5

[contracts.freelance-skill-verification_]
path = 'contracts/freelance-skill-verification_.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
